//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunnettRebalance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PunnettRebalance.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Abla&quot;,
        ///    &quot;Abrar&quot;,
        ///    &quot;Adalet&quot;,
        ///    &quot;Ahlam&quot;,
        ///    &quot;Aisha&quot;,
        ///    &quot;Aliyah&quot;,
        ///    &quot;Amal&quot;,
        ///    &quot;Amina&quot;,
        ///    &quot;Anisa&quot;,
        ///    &quot;Arwa&quot;,
        ///    &quot;Aya&quot;,
        ///    &quot;Aziza&quot;,
        ///    &quot;Azra&quot;,
        ///    &quot;Azza&quot;,
        ///    &quot;Calafia&quot;,
        ///    &quot;Dalia&quot;,
        ///    &quot;Dinara&quot;,
        ///    &quot;Dua&quot;,
        ///    &quot;Dunya&quot;,
        ///    &quot;Elif&quot;,
        ///    &quot;Elmira&quot;,
        ///    &quot;Fadia&quot;,
        ///    &quot;Faiza&quot;,
        ///    &quot;Farrah&quot;,
        ///    &quot;Fatima&quot;,
        ///    &quot;Fidda&quot;,
        ///    &quot;Ghada&quot;,
        ///    &quot;Hafsa&quot;,
        ///    &quot;Hala&quot;,
        ///    &quot;Halima&quot;,
        ///    &quot;Hana&quot;,
        ///    &quot;Hanifa&quot;,
        ///    &quot;Hayat&quot;,
        ///    &quot;Hayfa&quot;,
        ///    &quot;Huda&quot;,
        ///    &quot;Hum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DragonNames {
            get {
                return ResourceManager.GetString("DragonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: {
        ///    &quot;prefix&quot;: [
        ///      &quot;Anb&quot;,
        ///      &quot;Art&quot;,
        ///      &quot;Aud&quot;,
        ///      &quot;Bal&quot;,
        ///      &quot;Bar&quot;,
        ///      &quot;Bol&quot;,
        ///      &quot;Dag&quot;,
        ///      &quot;Daf&quot;,
        ///      &quot;Del&quot;,
        ///      &quot;Di&quot;,
        ///      &quot;H&quot;,
        ///      &quot;Eri&quot;,
        ///      &quot;Falk&quot;,
        ///      &quot;Fall&quot;,
        ///      &quot;Fine&quot;,
        ///      &quot;Gil&quot;,
        ///      &quot;Gun&quot;,
        ///      &quot;Gur&quot;,
        ///      &quot;Hel&quot;,
        ///      &quot;Hel&quot;,
        ///      &quot;Il&quot;,
        ///      &quot;Jar&quot;,
        ///      &quot;Ka&quot;,
        ///      &quot;Kil&quot;,
        ///      &quot;Kris&quot;,
        ///      &quot;Lif&quot;,
        ///      &quot;Maras&quot;,
        ///      &quot;Mar&quot;,
        ///      &quot;Mor&quot;,
        ///      &quot;Nal&quot;,
        ///      &quot;Nur&quot;,
        ///      &quot;Or&quot;,
        ///      &quot;Ov&quot;,
        ///      &quot;Ris&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DwarfNames {
            get {
                return ResourceManager.GetString("DwarfNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: {
        ///    &quot;prefix&quot;: [
        ///      &quot;Ael&quot;,
        ///      &quot;Aer&quot;,
        ///      &quot;Af&quot;,
        ///      &quot;Ah&quot;,
        ///      &quot;Al&quot;,
        ///      &quot;Am&quot;,
        ///      &quot;Ama&quot;,
        ///      &quot;An&quot;,
        ///      &quot;Ang&quot;,
        ///      &quot;Ansr&quot;,
        ///      &quot;Ar&quot;,
        ///      &quot;Arì&quot;,
        ///      &quot;Arn&quot;,
        ///      &quot;Aza&quot;,
        ///      &quot;Bael&quot;,
        ///      &quot;Bes&quot;,
        ///      &quot;Cael&quot;,
        ///      &quot;Cal&quot;,
        ///      &quot;Cas&quot;,
        ///      &quot;Cla&quot;,
        ///      &quot;Cor&quot;,
        ///      &quot;Cy&quot;,
        ///      &quot;Dae&quot;,
        ///      &quot;Dho&quot;,
        ///      &quot;Dre&quot;,
        ///      &quot;Du&quot;,
        ///      &quot;Eil&quot;,
        ///      &quot;Eir&quot;,
        ///      &quot;El&quot;,
        ///      &quot;Er&quot;,
        ///      &quot;Ev&quot;,
        ///      &quot;Fera&quot;,
        ///      &quot;Fi&quot;,
        ///      &quot;Fir&quot;,
        ///      &quot;Fis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ElfNames {
            get {
                return ResourceManager.GetString("ElfNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Treech&quot;,
        ///    &quot;Xord&quot;,
        ///    &quot;Vacs&quot;,
        ///    &quot;Krart&quot;,
        ///    &quot;Ult&quot;,
        ///    &quot;Sbylom&quot;,
        ///    &quot;Shiogtelm&quot;,
        ///    &quot;Weilt&quot;,
        ///    &quot;Svac&quot;,
        ///    &quot;Stoiv&quot;,
        ///    &quot;Zir&quot;,
        ///    &quot;Klegion&quot;,
        ///    &quot;Eeczs&quot;,
        ///    &quot;Dowkat&quot;,
        ///    &quot;Mildirie&quot;,
        ///    &quot;Aqaf&quot;,
        ///    &quot;Nocten&quot;,
        ///    &quot;Krovzat&quot;,
        ///    &quot;Pirg&quot;,
        ///    &quot;Blihber&quot;,
        ///    &quot;Kezz&quot;,
        ///    &quot;Brost&quot;,
        ///    &quot;Heepvogs&quot;,
        ///    &quot;Gehkiaz&quot;,
        ///    &quot;Riohgolma&quot;,
        ///    &quot;Cerkx&quot;,
        ///    &quot;Bryd&quot;,
        ///    &quot;Bidexhai&quot;,
        ///    &quot;Gam&quot;,
        ///    &quot;Kluithea&quot;,
        ///    &quot;Teeq&quot;,
        ///    &quot;Steguish&quot;,
        ///    &quot;Sluz&quot;,
        ///    &quot;Huyr&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoblinNames {
            get {
                return ResourceManager.GetString("GoblinNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Aerona&quot;,
        ///    &quot;Afanen&quot;,
        ///    &quot;Alaw&quot;,
        ///    &quot;Alys&quot;,
        ///    &quot;Angharad&quot;,
        ///    &quot;Argoel&quot;,
        ///    &quot;Arianwen&quot;,
        ///    &quot;Arlais&quot;,
        ///    &quot;Aures&quot;,
        ///    &quot;Beca&quot;,
        ///    &quot;Bethan&quot;,
        ///    &quot;Betrys&quot;,
        ///    &quot;Briallen&quot;,
        ///    &quot;Bronwyn&quot;,
        ///    &quot;Caraf&quot;,
        ///    &quot;Cari&quot;,
        ///    &quot;Caron&quot;,
        ///    &quot;Catrin&quot;,
        ///    &quot;Ceridwen&quot;,
        ///    &quot;Cerys&quot;,
        ///    &quot;Cymreiges&quot;,
        ///    &quot;Daron&quot;,
        ///    &quot;Del&quot;,
        ///    &quot;Delyth&quot;,
        ///    &quot;Deryn&quot;,
        ///    &quot;Dilys&quot;,
        ///    &quot;Disgleirio&quot;,
        ///    &quot;Ebril&quot;,
        ///    &quot;Efa&quot;,
        ///    &quot;Eira&quot;,
        ///    &quot;Enid&quot;,
        ///    &quot;Eres&quot;,
        ///    &quot;Eurolwyn&quot;,
        ///    &quot;Ffanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HitsujiNames {
            get {
                return ResourceManager.GetString("HitsujiNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Aadhya&quot;,
        ///    &quot;Aaliyah&quot;,
        ///    &quot;Abby&quot;,
        ///    &quot;Abigail&quot;,
        ///    &quot;Ada&quot;,
        ///    &quot;Adalee&quot;,
        ///    &quot;Adaline&quot;,
        ///    &quot;Adalyn&quot;,
        ///    &quot;Adalynn&quot;,
        ///    &quot;Addilyn&quot;,
        ///    &quot;Addilynn&quot;,
        ///    &quot;Addison&quot;,
        ///    &quot;Adelaide&quot;,
        ///    &quot;Adele&quot;,
        ///    &quot;Adelina&quot;,
        ///    &quot;Adeline&quot;,
        ///    &quot;Adelyn&quot;,
        ///    &quot;Adelynn&quot;,
        ///    &quot;Adley&quot;,
        ///    &quot;Adriana&quot;,
        ///    &quot;Adrianna&quot;,
        ///    &quot;Aila&quot;,
        ///    &quot;Ailani&quot;,
        ///    &quot;Aileen&quot;,
        ///    &quot;Ainhoa&quot;,
        ///    &quot;Ainsley&quot;,
        ///    &quot;Aisha&quot;,
        ///    &quot;Aitana&quot;,
        ///    &quot;Alaia&quot;,
        ///    &quot;Alaina&quot;,
        ///    &quot;Alaiya&quot;,
        ///    &quot;Alana&quot;,
        ///    &quot;Alani [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HumanNames {
            get {
                return ResourceManager.GetString("HumanNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Ae-Cha&quot;,
        ///    &quot;Ari&quot;,
        ///    &quot;Binna&quot;,
        ///    &quot;Bora&quot;,
        ///    &quot;Boram&quot;,
        ///    &quot;Chae-Won&quot;,
        ///    &quot;Chae-Yeong&quot;,
        ///    &quot;Da-Eun&quot;,
        ///    &quot;Dal-Rae&quot;,
        ///    &quot;Dam-Bi&quot;,
        ///    &quot;Dan-Bi&quot;,
        ///    &quot;Da-Som&quot;,
        ///    &quot;Duri&quot;,
        ///    &quot;Eun-Jeong&quot;,
        ///    &quot;Eun-Ji&quot;,
        ///    &quot;Eun-Ju&quot;,
        ///    &quot;Eun-Jung&quot;,
        ///    &quot;Eun-Kyung&quot;,
        ///    &quot;Eun-Sook&quot;,
        ///    &quot;Eun-Young&quot;,
        ///    &quot;Ga-Ram&quot;,
        ///    &quot;Geumseong&quot;,
        ///    &quot;Geu-Roo&quot;,
        ///    &quot;Gyeong&quot;,
        ///    &quot;Gyeong-Hui&quot;,
        ///    &quot;Gyeong-Ja&quot;,
        ///    &quot;Gyeong-Suk&quot;,
        ///    &quot;Gyeo-Wool&quot;,
        ///    &quot;Ha-Eun&quot;,
        ///    &quot;Hana&quot;,
        ///    &quot;Ha-Yun&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InuNames {
            get {
                return ResourceManager.GetString("InuNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Achilles&quot;,
        ///    &quot;Aegeus&quot;,
        ///    &quot;Aikat&quot;,
        ///    &quot;Ajax&quot;,
        ///    &quot;Akakios&quot;,
        ///    &quot;Alcaeus&quot;,
        ///    &quot;Alexandros&quot;,
        ///    &quot;Alexis&quot;,
        ///    &quot;Anargyros&quot;,
        ///    &quot;Anastasios&quot;,
        ///    &quot;Andreas&quot;,
        ///    &quot;Androcles&quot;,
        ///    &quot;Angelos&quot;,
        ///    &quot;Antigonus&quot;,
        ///    &quot;Antonios&quot;,
        ///    &quot;Apostolos&quot;,
        ///    &quot;Aris&quot;,
        ///    &quot;Aristeidis&quot;,
        ///    &quot;Athan&quot;,
        ///    &quot;Charalampos&quot;,
        ///    &quot;Charilaos&quot;,
        ///    &quot;Christos – Version One&quot;,
        ///    &quot;Christos – Version Two&quot;,
        ///    &quot;Chrysanthos&quot;,
        ///    &quot;Chrysostomos&quot;,
        ///    &quot;Cleon&quot;,
        ///    &quot;Costas&quot;,
        ///    &quot;Cyrus&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MinotaurNames {
            get {
                return ResourceManager.GetString("MinotaurNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Ai&quot;,
        ///    &quot;Aiko&quot;,
        ///    &quot;Aimi&quot;,
        ///    &quot;Aina&quot;,
        ///    &quot;Airi&quot;,
        ///    &quot;Akane&quot;,
        ///    &quot;Akari&quot;,
        ///    &quot;Akemi&quot;,
        ///    &quot;Aki&quot;,
        ///    &quot;Akiko&quot;,
        ///    &quot;Akira&quot;,
        ///    &quot;Ami&quot;,
        ///    &quot;Aoi&quot;,
        ///    &quot;Asami&quot;,
        ///    &quot;Asuka&quot;,
        ///    &quot;Atsuko&quot;,
        ///    &quot;Aya&quot;,
        ///    &quot;Ayaka&quot;,
        ///    &quot;Ayako&quot;,
        ///    &quot;Ayame&quot;,
        ///    &quot;Ayane&quot;,
        ///    &quot;Chiaki&quot;,
        ///    &quot;Chie&quot;,
        ///    &quot;Chihiro&quot;,
        ///    &quot;Chika&quot;,
        ///    &quot;Chikako&quot;,
        ///    &quot;Chinatsu&quot;,
        ///    &quot;Chiyo&quot;,
        ///    &quot;Chiyoko&quot;,
        ///    &quot;Chō&quot;,
        ///    &quot;Ema&quot;,
        ///    &quot;Emi&quot;,
        ///    &quot;Etsuko&quot;,
        ///    &quot;Fusae&quot;,
        ///    &quot;Fuyuko&quot;,
        ///    &quot;Hana&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NekoNames {
            get {
                return ResourceManager.GetString("NekoNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Abbarth&quot;,
        ///    &quot;Alfaeldssen&quot;,
        ///    &quot;Algbal&quot;,
        ///    &quot;Alimi&quot;,
        ///    &quot;Alldrich&quot;,
        ///    &quot;Aloral&quot;,
        ///    &quot;Alrahrikson&quot;,
        ///    &quot;Angne&quot;,
        ///    &quot;Anur&quot;,
        ///    &quot;Argarokssen&quot;,
        ///    &quot;Asarsson&quot;,
        ///    &quot;Asbdan&quot;,
        ///    &quot;Aslot&quot;,
        ///    &quot;Asornssen&quot;,
        ///    &quot;Axesnarl&quot;,
        ///    &quot;Bear&quot;,
        ///    &quot;Bloody&quot;,
        ///    &quot;Bonefang&quot;,
        ///    &quot;Ces&quot;,
        ///    &quot;Cook&quot;,
        ///    &quot;Deathbrand&quot;,
        ///    &quot;Deep&quot;,
        ///    &quot;Dernam&quot;,
        ///    &quot;Deth&quot;,
        ///    &quot;Dosk&quot;,
        ///    &quot;Dotard&quot;,
        ///    &quot;Drynarinn&quot;,
        ///    &quot;Ehrensvesen&quot;,
        ///    &quot;Ember&quot;,
        ///    &quot;Eraslo&quot;,
        ///    &quot;Fanralderssen&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrcNames {
            get {
                return ResourceManager.GetString("OrcNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Aamadu&quot;,
        ///    &quot;Abidemi&quot;,
        ///    &quot;Aboubacar&quot;,
        ///    &quot;Ade&quot;,
        ///    &quot;Akpan&quot;,
        ///    &quot;Akpofure&quot;,
        ///    &quot;Alassane&quot;,
        ///    &quot;Alemayehu&quot;,
        ///    &quot;Amadi&quot;,
        ///    &quot;Ameqran&quot;,
        ///    &quot;Ayomide&quot;,
        ///    &quot;Azubuike&quot;,
        ///    &quot;Berhane&quot;,
        ///    &quot;Bitrus&quot;,
        ///    &quot;Bongani&quot;,
        ///    &quot;Cali&quot;,
        ///    &quot;Cardiraxman&quot;,
        ///    &quot;Chibuike&quot;,
        ///    &quot;Chikondi&quot;,
        ///    &quot;Chima&quot;,
        ///    &quot;Chinasa&quot;,
        ///    &quot;Chiumbo&quot;,
        ///    &quot;Chiyembekezo&quot;,
        ///    &quot;Chucks&quot;,
        ///    &quot;Dakarai&quot;,
        ///    &quot;Dawit&quot;,
        ///    &quot;Dejen&quot;,
        ///    &quot;Desta&quot;,
        ///    &quot;Ebrima&quot;,
        ///    &quot;Efe&quot;,
        ///    &quot;Ejiro&quot;,
        ///    &quot;Ekene [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalamanderNames {
            get {
                return ResourceManager.GetString("SalamanderNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Abeque&quot;,
        ///    &quot;Agisa&quot;,
        ///    &quot;Aiukli&quot;,
        ///    &quot;Alaska&quot;,
        ///    &quot;Angeni&quot;,
        ///    &quot;Aponi&quot;,
        ///    &quot;Aquinnah&quot;,
        ///    &quot;Ashwiyaa&quot;,
        ///    &quot;Atabey&quot;,
        ///    &quot;Atina&quot;,
        ///    &quot;Awe&quot;,
        ///    &quot;Aylin&quot;,
        ///    &quot;Byhalia&quot;,
        ///    &quot;Chaha&quot;,
        ///    &quot;Chepi&quot;,
        ///    &quot;Cheyenne&quot;,
        ///    &quot;Cholena&quot;,
        ///    &quot;Dahteste&quot;,
        ///    &quot;Dakota&quot;,
        ///    &quot;Doli&quot;,
        ///    &quot;Dyani&quot;,
        ///    &quot;Ewa&quot;,
        ///    &quot;Eyota&quot;,
        ///    &quot;Godasiyo&quot;,
        ///    &quot;Gouyen&quot;,
        ///    &quot;Hateya&quot;,
        ///    &quot;Hurit&quot;,
        ///    &quot;Iara&quot;,
        ///    &quot;Illari&quot;,
        ///    &quot;Issi&quot;,
        ///    &quot;Kachina&quot;,
        ///    &quot;Kaniehtiio&quot;,
        ///    &quot;Kateri&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsagiNames {
            get {
                return ResourceManager.GetString("UsagiNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;names&quot;: [
        ///    &quot;Aidan&quot;,
        ///    &quot;Aldis&quot;,
        ///    &quot;Alfie&quot;,
        ///    &quot;Alfred&quot;,
        ///    &quot;Alistair&quot;,
        ///    &quot;Archibald&quot;,
        ///    &quot;Arthur&quot;,
        ///    &quot;Basil&quot;,
        ///    &quot;Benedict&quot;,
        ///    &quot;Benjamin&quot;,
        ///    &quot;Bertram&quot;,
        ///    &quot;Blake&quot;,
        ///    &quot;Byron&quot;,
        ///    &quot;Caledon&quot;,
        ///    &quot;Callum&quot;,
        ///    &quot;Cameron&quot;,
        ///    &quot;Carew&quot;,
        ///    &quot;Charlie&quot;,
        ///    &quot;Christopher&quot;,
        ///    &quot;Cillian&quot;,
        ///    &quot;Cooper&quot;,
        ///    &quot;Crispin&quot;,
        ///    &quot;Damian&quot;,
        ///    &quot;Daniel&quot;,
        ///    &quot;Dean&quot;,
        ///    &quot;Desmond&quot;,
        ///    &quot;Devon&quot;,
        ///    &quot;Duncan&quot;,
        ///    &quot;Dwight&quot;,
        ///    &quot;Earl&quot;,
        ///    &quot;Edgar&quot;,
        ///    &quot;Edmund&quot;,
        ///    &quot;El [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WerewolfNames {
            get {
                return ResourceManager.GetString("WerewolfNames", resourceCulture);
            }
        }
    }
}
